redid configs

diff --git a/unicorn_init b/unicorn_init
--- a/unicorn_init
+++ b/unicorn_init
@@ -1,92 +1,70 @@
 #!/bin/sh
-#
-# init.d script for single or multiple unicorn installations. Expects at least one .conf 
-# file in /etc/unicorn
-#
-# Modified by jay@gooby.org http://github.com/jaygooby
-# based on http://gist.github.com/308216 by http://github.com/mguterl
-#
-## A sample /etc/unicorn/my_app.conf
-## 
-## RAILS_ENV=production
-## RAILS_ROOT=/var/apps/www/my_app/current
-#
-# This configures a unicorn master for your app at /var/apps/www/my_app/current running in
-# production mode. It will read config/unicorn.rb for further set up. 
-#
-# You should ensure different ports or sockets are set in each config/unicorn.rb if
-# you are running more than one master concurrently.
-#
-# If you call this script without any config parameters, it will attempt to run the
-# init command for all your unicorn configurations listed in /etc/unicorn/*.conf
-#
-# /etc/init.d/unicorn start # starts all unicorns
-#
-# If you specify a particular config, it will only operate on that one
-#
-# /etc/init.d/unicorn start /etc/unicorn/my_app.conf
  
+### BEGIN INIT INFO
+# Provides:          unicorn
+# Required-Start:    $local_fs $remote_fs
+# Required-Stop:     $local_fs $remote_fs
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: starts unicorn
+# Description:       starts uniconr using start-stop-daemon
+### END INIT INFO
+ 
+set -u
 set -e
  
-cmd () {
+export PATH=$HOME/.rbenv/bin:$PATH
+export RBENV_DIR=$HOME/.rbenv
+export RBENV_ROOT=$HOME/.rbenv
  
-  case $1 in
-    start)
-      echo $DAEMON_OPTS
-      start-stop-daemon --start --quiet --pidfile $PID \
-                --exec $DAEMON -- $DAEMON_OPTS || true
-      echo "Starting with config: $RAILS_ROOT/config/unicorn.rb"
-      ;;  
-    stop)
-      start-stop-daemon --stop --quiet --pidfile $PID || true
-      echo "Stopping with config: $RAILS_ROOT/config/unicorn.rb"
-      ;;  
-    restart|reload)
-      start-stop-daemon --stop --quiet --pidfile $PID || true
-      echo "Stopping with config: $RAILS_ROOT/config/unicorn.rb"
-      sleep 1
-      start-stop-daemon --start --quiet --pidfile $PID \
-                --exec $DAEMON -- $DAEMON_OPTS || true
-      echo "Starting with config: $RAILS_ROOT/config/unicorn.rb"
-      ;;  
-    *)  
-      echo >&2 "Usage: $0 <start|stop|restart>"
-      exit 1
-      ;;  
-    esac
+APP_ROOT=/usr/local/helloworld
+PID=$APP_ROOT/tmp/pids/unicorn.pid
+RAILS_ENV=production
+ 
+export PATH="$RBENV_ROOT/shims:$RBENV_ROOT/rbenv:$PATH"
+CMD="bundle exec $RBENV_ROOT/shims/unicorn -D -E $RAILS_ENV -c config/unicorn.rb"
+ 
+ 
+old_pid="$PID.oldbin"
+ 
+cd $APP_ROOT || exit 1
+ 
+sig () {
+    test -s "$PID" && kill -$1 `cat $PID`
 }
  
-setup () {
- 
-  export PID=$RAILS_ROOT/tmp/pids/unicorn.pid
-  export OLD_PID="$PID.oldbin"
- 
-  DAEMON="`which unicorn_rails`"
-  DAEMON_OPTS="-c $RAILS_ROOT/config/unicorn.rb -E $RAILS_ENV -D"
+oldsig () {
+    test -s $old_pid && kill -$1 `cat $old_pid`
 }
  
-start_stop () {
-  
-  # either run the start/stop/reload/etc command for every config under /etc/unicorn
-  # or just do it for a specific one
- 
-  # $1 contains the start/stop/etc command
-  # $2 if it exists, should be the specific config we want to act on
-  if [ $2 ]; then
-    . $2
-    setup
-    cmd $1
-  else
-    for CONFIG in /etc/unicorn/*.conf; do
-      # import the variables
-      . $CONFIG
-      setup
- 
-      # run the start/stop/etc command
-      cmd $1
-    done
-   fi
-}
- 
-ARGS="$1 $2"
-start_stop $ARGS
+case $1 in
+start)
+    sig 0 && echo >&2 "Already running" && exit 0
+    $CMD
+    ;;
+stop)
+    sig QUIT && exit 0
+    echo >&2 "Not running"
+    ;;
+force-stop)
+    sig TERM && 0
+    echo >&2 "Not running"
+    ;;
+restart|reload)
+    sig HUP && echo reloaded OK && exit 0
+    echo >&2 "Couldn't reload, starting '$CMD' instead"
+    $CMD
+    ;;
+upgrade)
+    sig USR2 && exit 0
+    echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+    ;;
+rotate)
+    sig USR1 && echo rotated logs OK && exit 0
+    echo >&2 "Couldn't rotate logs" && 1
+    ;;
+*)
+    echo >&2 "Usage $0 <start|stop|restart|upgrade|rotate|force-stop>"
+    exit 1
+    ;;
+esac
